CREATE DATABASE covid;

-- CREATE LOGIN apiUserLogin WITH PASSWORD = 'KVpNLrA9z4n95RpNH0Cm5uwy8vCCPOaz';
-- CREATE USER apiUser WITH PASSWORD KVpNLrA9z4n95RpNH0Cm5uwy8vCCPOaz;
CREATE USER apiUser WITH PASSWORD 'jw8s0F5';
GRANT ALL PRIVILEGES ON DATABASE covid TO apiUser;

CREATE USER guetUser;
GRANT CONNECT ON DATABASE covid TO guetUser;
-- GRANT SELECT TO guetUser;

