CREATE DATABASE covid;

CREATE USER apiUser WITH PASSWORD 'kredenc123';
GRANT ALL PRIVILEGES ON DATABASE covid TO apiUser;


CREATE SCHEMA covidData;
CREATE TABLE covidData.test_table
(
  id INT PRIMARY KEY,
  username VARCHAR (50) NOT NULL,
  realname VARCHAR (50) NOT NULL,
  email VARCHAR (255) NOT NULL
);
